service: sls-az-func-rest-api

provider:
  name: azure
  region: Central US # IMPORTANT
  runtime: nodejs10.x # IMPORTANT

  environment:
    VARIABLE_FOO: 'foo'

plugins:
  - serverless-azure-functions

package:
  exclude:
    - local.settings.json
    - .vscode/**

functions:
  issues:
    invoices: src/handlers/invoices.handler
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous